baseURL = 'https://ca115.wizzdom.xyz/'
languageCode = 'en-us'
theme = 'graysx'
title = 'NovaScape NS-1'

## Site Settings
[params]
logo = "assets/img/logo.png"
favicon = "assets/favicon.png"

# Info
address = "Dublin City University, DCU Glasnevin Campus, Dublin 9, Ireland"
email = "wizzdom@redbrick.dcu.ie"
phone = "12345678"

# Socials

# twitter = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
# facebook = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
github = "https://github.com/wizzdom/ca115-project"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
# sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "Product Description"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Market Research Survey"
  URL = "https://forms.gle/Ng8LkiLSxPTmtYoL7"
  weight = 2

  [[menu.main]]
  name = "Product Pricing"
  URL = "#projects"
  weight = 3

  [[menu.main]]
  name = "Team Contact"
  URL = "#signup"
  weight = 4


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04
